### ISSUE TITLE
Adapter plötzlich im restart-loop 

### ISSUE THREAD

**Issue by JohGrei** [iobroker-community-adapters/ioBroker.botvac#46]
Hallo,

plötzlich heute morgen hat der Adapter Fehler geworfen und ist in den Restart loop gekommen und ist dann vom js-controller deaktiviert worden. Anbei die Info-Log aus dieser Zeit. 
Was möglicherweise der Auslöser sein könnte ist, dass einer der Roboter nicht erreichbar ist. Steht in einem andern Haus und dort dürfte gerade das Internet nicht funktionieren. Aber kann das den Adapter niederreissen?

edit: Nachdem der Roboter wieder im Netz war ließ sich der Adapter wieder problemlos starten.

```2023-09-19 08:01:00.704 - warn: botvac.0 (57835) could not update robot Turnverein Oben
2023-09-19 08:01:00.705 - warn: botvac.0 (57835) could not update robot Turnverein Oben
2023-09-19 08:01:00.709 - warn: botvac.0 (57835) Read-only state "botvac.0.Turnverein Oben.status.reachable" has been written without ack-flag with value "true"
2023-09-19 08:01:00.755 - warn: botvac.0 (57835) Read-only state "botvac.0.Turnverein Oben.status.reachable" has been written without ack-flag with value "true"
2023-09-19 08:02:14.587 - warn: botvac.0 (57835) could not update robot Turnverein Oben
2023-09-19 08:02:16.367 - info: botvac.0 (57835) devices found: 3
2023-09-19 08:02:16.395 - warn: botvac.0 (57835) Device"Turnverein Oben" with id: Turnverein Oben is not exists in cloud any more!
2023-09-19 08:02:16.635 - warn: botvac.0 (57835) Device"Erdgeschoss" with id: Erdgeschoss is not exists in cloud any more!
2023-09-19 08:02:16.636 - warn: botvac.0 (57835) Device"Turnverein Oben" with id: Turnverein Oben is not exists in cloud any more!
2023-09-19 08:02:16.969 - warn: botvac.0 (57835) Device"Erdgeschoss" with id: Erdgeschoss is not exists in cloud any more!
2023-09-19 08:02:16.969 - warn: botvac.0 (57835) Device"Keller" with id: Keller is not exists in cloud any more!
2023-09-19 08:02:16.969 - warn: botvac.0 (57835) Device"Turnverein Oben" with id: Turnverein Oben is not exists in cloud any more!
2023-09-19 08:02:17.201 - error: botvac.0 (57835) uncaught exception: Cannot read properties of undefined (reading 'getState')
2023-09-19 08:02:17.202 - error: botvac.0 (57835) TypeError: Cannot read properties of undefined (reading 'getState')
at updateRobot (/opt/iobroker/node_modules/iobroker.botvac/main.js:476:11)
at update (/opt/iobroker/node_modules/iobroker.botvac/main.js:467:9)
at Immediate. (/opt/iobroker/node_modules/iobroker.botvac/main.js:456:25)
at process.processImmediate (node:internal/timers:478:21)
2023-09-19 08:02:17.203 - error: botvac.0 (57835) Cannot read properties of undefined (reading 'getState')
2023-09-19 08:02:17.224 - info: botvac.0 (57835) terminating
2023-09-19 08:02:17.225 - warn: botvac.0 (57835) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-09-19 08:02:17.729 - info: botvac.0 (57835) terminating
2023-09-19 08:02:17.844 - error: host.VM-Slave instance system.adapter.botvac.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-09-19 08:02:49.398 - info: botvac.0 (78675) starting. Version 2.0.0-alpha.1 (non-npm: iobroker-community-adapters/ioBroker.botvac#48bc291c4416ec4a5393cecf340ec39162a7138c) in /opt/iobroker/node_modules/iobroker.botvac, node: v18.17.1, js-controller: 5.0.12
2023-09-19 08:02:51.991 - warn: botvac.0 (78675) could not update robot Turnverein Oben
2023-09-19 08:02:54.176 - info: botvac.0 (78675) devices found: 3
2023-09-19 08:02:54.209 - warn: botvac.0 (78675) Device"Turnverein Oben" with id: Turnverein Oben is not exists in cloud any more!
2023-09-19 08:02:54.558 - warn: botvac.0 (78675) Device"Erdgeschoss" with id: Erdgeschoss is not exists in cloud any more!
2023-09-19 08:02:54.559 - warn: botvac.0 (78675) Device"Turnverein Oben" with id: Turnverein Oben is not exists in cloud any more!
2023-09-19 08:02:54.826 - warn: botvac.0 (78675) Device"Erdgeschoss" with id: Erdgeschoss is not exists in cloud any more!
2023-09-19 08:02:54.826 - warn: botvac.0 (78675) Device"Keller" with id: Keller is not exists in cloud any more!
2023-09-19 08:02:54.827 - warn: botvac.0 (78675) Device"Turnverein Oben" with id: Turnverein Oben is not exists in cloud any more!
2023-09-19 08:02:55.079 - error: botvac.0 (78675) uncaught exception: Cannot read properties of undefined (reading 'getState')
2023-09-19 08:02:55.080 - error: botvac.0 (78675) TypeError: Cannot read properties of undefined (reading 'getState')
at updateRobot (/opt/iobroker/node_modules/iobroker.botvac/main.js:476:11)
at update (/opt/iobroker/node_modules/iobroker.botvac/main.js:467:9)
at Immediate. (/opt/iobroker/node_modules/iobroker.botvac/main.js:456:25)
at process.processImmediate (node:internal/timers:478:21)
2023-09-19 08:02:55.081 - error: botvac.0 (78675) Cannot read properties of undefined (reading 'getState')
2023-09-19 08:02:55.109 - info: botvac.0 (78675) terminating
2023-09-19 08:02:55.110 - warn: botvac.0 (78675) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-09-19 08:02:55.611 - info: botvac.0 (78675) terminating
2023-09-19 08:02:55.735 - error: host.VM-Slave instance system.adapter.botvac.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-09-19 08:03:27.330 - info: botvac.0 (78704) starting. Version 2.0.0-alpha.1 (non-npm: iobroker-community-adapters/ioBroker.botvac#48bc291c4416ec4a5393cecf340ec39162a7138c) in /opt/iobroker/node_modules/iobroker.botvac, node: v18.17.1, js-controller: 5.0.12
2023-09-19 08:03:29.998 - warn: botvac.0 (78704) could not update robot Turnverein Oben
2023-09-19 08:03:32.148 - info: botvac.0 (78704) devices found: 3
2023-09-19 08:03:32.179 - warn: botvac.0 (78704) Device"Turnverein Oben" with id: Turnverein Oben is not exists in cloud any more!
2023-09-19 08:03:32.490 - warn: botvac.0 (78704) Device"Erdgeschoss" with id: Erdgeschoss is not exists in cloud any more!
2023-09-19 08:03:32.491 - warn: botvac.0 (78704) Device"Turnverein Oben" with id: Turnverein Oben is not exists in cloud any more!
2023-09-19 08:03:32.800 - warn: botvac.0 (78704) Device"Erdgeschoss" with id: Erdgeschoss is not exists in cloud any more!
2023-09-19 08:03:32.801 - warn: botvac.0 (78704) Device"Keller" with id: Keller is not exists in cloud any more!
2023-09-19 08:03:32.801 - warn: botvac.0 (78704) Device"Turnverein Oben" with id: Turnverein Oben is not exists in cloud any more!
2023-09-19 08:03:33.006 - error: botvac.0 (78704) uncaught exception: Cannot read properties of undefined (reading 'getState')
2023-09-19 08:03:33.007 - error: botvac.0 (78704) TypeError: Cannot read properties of undefined (reading 'getState')
at updateRobot (/opt/iobroker/node_modules/iobroker.botvac/main.js:476:11)
at update (/opt/iobroker/node_modules/iobroker.botvac/main.js:467:9)
at Immediate. (/opt/iobroker/node_modules/iobroker.botvac/main.js:456:25)
at process.processImmediate (node:internal/timers:478:21)
2023-09-19 08:03:33.008 - error: botvac.0 (78704) Cannot read properties of undefined (reading 'getState')
2023-09-19 08:03:33.037 - info: botvac.0 (78704) terminating
2023-09-19 08:03:33.039 - warn: botvac.0 (78704) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-09-19 08:03:33.540 - info: botvac.0 (78704) terminating
2023-09-19 08:03:33.677 - error: host.VM-Slave instance system.adapter.botvac.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-09-19 08:03:33.678 - warn: host.VM-Slave Do not restart adapter system.adapter.botvac.0 because restart loop detected
```

**Comment by PeterVoronov** [comment]
> Hallo,
> 
> plötzlich heute morgen hat der Adapter Fehler geworfen und ist in den Restart loop gekommen und ist dann vom js-controller deaktiviert worden. Anbei die Info-Log aus dieser Zeit. Was möglicherweise der Auslöser sein könnte ist, dass einer der Roboter nicht erreichbar ist. Steht in einem andern Haus und dort dürfte gerade das Internet nicht funktionieren. Aber kann das den Adapter niederreissen?
> 
> edit: Nachdem der Roboter wieder im Netz war ließ sich der Adapter wieder problemlos starten.


Use code brackets for the logs, otherwise it's not readable ...
![image](https://github.com/iobroker-community-adapters/ioBroker.botvac/assets/66964358/4c73943f-b575-4af6-807b-a65cecd62768)
And, if possible - enable debug before it ...

P.S. Appropriate PR is ready

**Comment by mcm1957** [comment]
@PeterVoronov 
I do not see a PR yet. Please check.

**Comment by PeterVoronov** [comment]
> @PeterVoronov I do not see a PR yet. Please check.

Excuse me - not pressed last button - https://github.com/iobroker-community-adapters/ioBroker.botvac/pull/47

**Comment by mcm1957** [comment]
fixed with 2.0.1
